namespace Devolutions.Zxcvbn
{
    using System.Collections.Generic;

    internal class AdjacencyGraph : Dictionary<char, string[]>
    {
        public static AdjacencyGraph Qwerty = new AdjacencyGraph(nameof(Qwerty))
        {
            ['!'] = new[] { "`~", null, null, "2@", "qQ", null },
            ['"'] = new[] { ";:", "[{", "]}", null, null, "/?" },
            ['#'] = new[] { "2@", null, null, "4$", "eE", "wW" },
            ['$'] = new[] { "3#", null, null, "5%", "rR", "eE" },
            ['%'] = new[] { "4$", null, null, "6^", "tT", "rR" },
            ['&'] = new[] { "6^", null, null, "8*", "uU", "yY" },
            ['\''] = new[] { ";:", "[{", "]}", null, null, "/?" },
            ['('] = new[] { "8*", null, null, "0)", "oO", "iI" },
            [')'] = new[] { "9(", null, null, "-_", "pP", "oO" },
            ['*'] = new[] { "7&", null, null, "9(", "iI", "uU" },
            ['+'] = new[] { "-_", null, null, null, "]}", "[{" },
            [','] = new[] { "mM", "kK", "lL", ".>", null, null },
            ['-'] = new[] { "0)", null, null, "=+", "[{", "pP" },
            ['.'] = new[] { ",<", "lL", ";:", "/?", null, null },
            ['/'] = new[] { ".>", ";:", "'\"", null, null, null },
            ['0'] = new[] { "9(", null, null, "-_", "pP", "oO" },
            ['1'] = new[] { "`~", null, null, "2@", "qQ", null },
            ['2'] = new[] { "1!", null, null, "3#", "wW", "qQ" },
            ['3'] = new[] { "2@", null, null, "4$", "eE", "wW" },
            ['4'] = new[] { "3#", null, null, "5%", "rR", "eE" },
            ['5'] = new[] { "4$", null, null, "6^", "tT", "rR" },
            ['6'] = new[] { "5%", null, null, "7&", "yY", "tT" },
            ['7'] = new[] { "6^", null, null, "8*", "uU", "yY" },
            ['8'] = new[] { "7&", null, null, "9(", "iI", "uU" },
            ['9'] = new[] { "8*", null, null, "0)", "oO", "iI" },
            [':'] = new[] { "lL", "pP", "[{", "'\"", "/?", ".>" },
            [';'] = new[] { "lL", "pP", "[{", "'\"", "/?", ".>" },
            ['<'] = new[] { "mM", "kK", "lL", ".>", null, null },
            ['='] = new[] { "-_", null, null, null, "]}", "[{" },
            ['>'] = new[] { ",<", "lL", ";:", "/?", null, null },
            ['?'] = new[] { ".>", ";:", "'\"", null, null, null },
            ['@'] = new[] { "1!", null, null, "3#", "wW", "qQ" },
            ['A'] = new[] { null, "qQ", "wW", "sS", "zZ", null },
            ['B'] = new[] { "vV", "gG", "hH", "nN", null, null },
            ['C'] = new[] { "xX", "dD", "fF", "vV", null, null },
            ['D'] = new[] { "sS", "eE", "rR", "fF", "cC", "xX" },
            ['E'] = new[] { "wW", "3#", "4$", "rR", "dD", "sS" },
            ['F'] = new[] { "dD", "rR", "tT", "gG", "vV", "cC" },
            ['G'] = new[] { "fF", "tT", "yY", "hH", "bB", "vV" },
            ['H'] = new[] { "gG", "yY", "uU", "jJ", "nN", "bB" },
            ['I'] = new[] { "uU", "8*", "9(", "oO", "kK", "jJ" },
            ['J'] = new[] { "hH", "uU", "iI", "kK", "mM", "nN" },
            ['K'] = new[] { "jJ", "iI", "oO", "lL", ",<", "mM" },
            ['L'] = new[] { "kK", "oO", "pP", ";:", ".>", ",<" },
            ['M'] = new[] { "nN", "jJ", "kK", ",<", null, null },
            ['N'] = new[] { "bB", "hH", "jJ", "mM", null, null },
            ['O'] = new[] { "iI", "9(", "0)", "pP", "lL", "kK" },
            ['P'] = new[] { "oO", "0)", "-_", "[{", ";:", "lL" },
            ['Q'] = new[] { null, "1!", "2@", "wW", "aA", null },
            ['R'] = new[] { "eE", "4$", "5%", "tT", "fF", "dD" },
            ['S'] = new[] { "aA", "wW", "eE", "dD", "xX", "zZ" },
            ['T'] = new[] { "rR", "5%", "6^", "yY", "gG", "fF" },
            ['U'] = new[] { "yY", "7&", "8*", "iI", "jJ", "hH" },
            ['V'] = new[] { "cC", "fF", "gG", "bB", null, null },
            ['W'] = new[] { "qQ", "2@", "3#", "eE", "sS", "aA" },
            ['X'] = new[] { "zZ", "sS", "dD", "cC", null, null },
            ['Y'] = new[] { "tT", "6^", "7&", "uU", "hH", "gG" },
            ['Z'] = new[] { null, "aA", "sS", "xX", null, null },
            ['['] = new[] { "pP", "-_", "=+", "]}", "'\"", ";:" },
            ['\\'] = new[] { "]}", null, null, null, null, null },
            [']'] = new[] { "[{", "=+", null, "\\|", null, "'\"" },
            ['^'] = new[] { "5%", null, null, "7&", "yY", "tT" },
            ['_'] = new[] { "0)", null, null, "=+", "[{", "pP" },
            ['`'] = new[] { null, null, null, "1!", null, null },
            ['a'] = new[] { null, "qQ", "wW", "sS", "zZ", null },
            ['b'] = new[] { "vV", "gG", "hH", "nN", null, null },
            ['c'] = new[] { "xX", "dD", "fF", "vV", null, null },
            ['d'] = new[] { "sS", "eE", "rR", "fF", "cC", "xX" },
            ['e'] = new[] { "wW", "3#", "4$", "rR", "dD", "sS" },
            ['f'] = new[] { "dD", "rR", "tT", "gG", "vV", "cC" },
            ['g'] = new[] { "fF", "tT", "yY", "hH", "bB", "vV" },
            ['h'] = new[] { "gG", "yY", "uU", "jJ", "nN", "bB" },
            ['i'] = new[] { "uU", "8*", "9(", "oO", "kK", "jJ" },
            ['j'] = new[] { "hH", "uU", "iI", "kK", "mM", "nN" },
            ['k'] = new[] { "jJ", "iI", "oO", "lL", ",<", "mM" },
            ['l'] = new[] { "kK", "oO", "pP", ";:", ".>", ",<" },
            ['m'] = new[] { "nN", "jJ", "kK", ",<", null, null },
            ['n'] = new[] { "bB", "hH", "jJ", "mM", null, null },
            ['o'] = new[] { "iI", "9(", "0)", "pP", "lL", "kK" },
            ['p'] = new[] { "oO", "0)", "-_", "[{", ";:", "lL" },
            ['q'] = new[] { null, "1!", "2@", "wW", "aA", null },
            ['r'] = new[] { "eE", "4$", "5%", "tT", "fF", "dD" },
            ['s'] = new[] { "aA", "wW", "eE", "dD", "xX", "zZ" },
            ['t'] = new[] { "rR", "5%", "6^", "yY", "gG", "fF" },
            ['u'] = new[] { "yY", "7&", "8*", "iI", "jJ", "hH" },
            ['v'] = new[] { "cC", "fF", "gG", "bB", null, null },
            ['w'] = new[] { "qQ", "2@", "3#", "eE", "sS", "aA" },
            ['x'] = new[] { "zZ", "sS", "dD", "cC", null, null },
            ['y'] = new[] { "tT", "6^", "7&", "uU", "hH", "gG" },
            ['z'] = new[] { null, "aA", "sS", "xX", null, null },
            ['{'] = new[] { "pP", "-_", "=+", "]}", "'\"", ";:" },
            ['|'] = new[] { "]}", null, null, null, null, null },
            ['}'] = new[] { "[{", "=+", null, "\\|", null, "'\"" },
            ['~'] = new[] { null, null, null, "1!", null, null }
        };

        public static AdjacencyGraph Dvorak = new AdjacencyGraph(nameof(Dvorak))
        {
            ['!'] = new[] { "`~", null, null, "2@", "'\"", null },
            ['"'] = new[] { null, "1!", "2@", ",<", "aA", null },
            ['#'] = new[] { "2@", null, null, "4$", ".>", ",<" },
            ['$'] = new[] { "3#", null, null, "5%", "pP", ".>" },
            ['%'] = new[] { "4$", null, null, "6^", "yY", "pP" },
            ['&'] = new[] { "6^", null, null, "8*", "gG", "fF" },
            ['\''] = new[] { null, "1!", "2@", ",<", "aA", null },
            ['('] = new[] { "8*", null, null, "0)", "rR", "cC" },
            [')'] = new[] { "9(", null, null, "[{", "lL", "rR" },
            ['*'] = new[] { "7&", null, null, "9(", "cC", "gG" },
            ['+'] = new[] { "/?", "]}", null, "\\|", null, "-_" },
            [','] = new[] { "'\"", "2@", "3#", ".>", "oO", "aA" },
            ['-'] = new[] { "sS", "/?", "=+", null, null, "zZ" },
            ['.'] = new[] { ",<", "3#", "4$", "pP", "eE", "oO" },
            ['/'] = new[] { "lL", "[{", "]}", "=+", "-_", "sS" },
            ['0'] = new[] { "9(", null, null, "[{", "lL", "rR" },
            ['1'] = new[] { "`~", null, null, "2@", "'\"", null },
            ['2'] = new[] { "1!", null, null, "3#", ",<", "'\"" },
            ['3'] = new[] { "2@", null, null, "4$", ".>", ",<" },
            ['4'] = new[] { "3#", null, null, "5%", "pP", ".>" },
            ['5'] = new[] { "4$", null, null, "6^", "yY", "pP" },
            ['6'] = new[] { "5%", null, null, "7&", "fF", "yY" },
            ['7'] = new[] { "6^", null, null, "8*", "gG", "fF" },
            ['8'] = new[] { "7&", null, null, "9(", "cC", "gG" },
            ['9'] = new[] { "8*", null, null, "0)", "rR", "cC" },
            [':'] = new[] { null, "aA", "oO", "qQ", null, null },
            [';'] = new[] { null, "aA", "oO", "qQ", null, null },
            ['<'] = new[] { "'\"", "2@", "3#", ".>", "oO", "aA" },
            ['='] = new[] { "/?", "]}", null, "\\|", null, "-_" },
            ['>'] = new[] { ",<", "3#", "4$", "pP", "eE", "oO" },
            ['?'] = new[] { "lL", "[{", "]}", "=+", "-_", "sS" },
            ['@'] = new[] { "1!", null, null, "3#", ",<", "'\"" },
            ['A'] = new[] { null, "'\"", ",<", "oO", ";:", null },
            ['B'] = new[] { "xX", "dD", "hH", "mM", null, null },
            ['C'] = new[] { "gG", "8*", "9(", "rR", "tT", "hH" },
            ['D'] = new[] { "iI", "fF", "gG", "hH", "bB", "xX" },
            ['E'] = new[] { "oO", ".>", "pP", "uU", "jJ", "qQ" },
            ['F'] = new[] { "yY", "6^", "7&", "gG", "dD", "iI" },
            ['G'] = new[] { "fF", "7&", "8*", "cC", "hH", "dD" },
            ['H'] = new[] { "dD", "gG", "cC", "tT", "mM", "bB" },
            ['I'] = new[] { "uU", "yY", "fF", "dD", "xX", "kK" },
            ['J'] = new[] { "qQ", "eE", "uU", "kK", null, null },
            ['K'] = new[] { "jJ", "uU", "iI", "xX", null, null },
            ['L'] = new[] { "rR", "0)", "[{", "/?", "sS", "nN" },
            ['M'] = new[] { "bB", "hH", "tT", "wW", null, null },
            ['N'] = new[] { "tT", "rR", "lL", "sS", "vV", "wW" },
            ['O'] = new[] { "aA", ",<", ".>", "eE", "qQ", ";:" },
            ['P'] = new[] { ".>", "4$", "5%", "yY", "uU", "eE" },
            ['Q'] = new[] { ";:", "oO", "eE", "jJ", null, null },
            ['R'] = new[] { "cC", "9(", "0)", "lL", "nN", "tT" },
            ['S'] = new[] { "nN", "lL", "/?", "-_", "zZ", "vV" },
            ['T'] = new[] { "hH", "cC", "rR", "nN", "wW", "mM" },
            ['U'] = new[] { "eE", "pP", "yY", "iI", "kK", "jJ" },
            ['V'] = new[] { "wW", "nN", "sS", "zZ", null, null },
            ['W'] = new[] { "mM", "tT", "nN", "vV", null, null },
            ['X'] = new[] { "kK", "iI", "dD", "bB", null, null },
            ['Y'] = new[] { "pP", "5%", "6^", "fF", "iI", "uU" },
            ['Z'] = new[] { "vV", "sS", "-_", null, null, null },
            ['['] = new[] { "0)", null, null, "]}", "/?", "lL" },
            ['\\'] = new[] { "=+", null, null, null, null, null },
            [']'] = new[] { "[{", null, null, null, "=+", "/?" },
            ['^'] = new[] { "5%", null, null, "7&", "fF", "yY" },
            ['_'] = new[] { "sS", "/?", "=+", null, null, "zZ" },
            ['`'] = new[] { null, null, null, "1!", null, null },
            ['a'] = new[] { null, "'\"", ",<", "oO", ";:", null },
            ['b'] = new[] { "xX", "dD", "hH", "mM", null, null },
            ['c'] = new[] { "gG", "8*", "9(", "rR", "tT", "hH" },
            ['d'] = new[] { "iI", "fF", "gG", "hH", "bB", "xX" },
            ['e'] = new[] { "oO", ".>", "pP", "uU", "jJ", "qQ" },
            ['f'] = new[] { "yY", "6^", "7&", "gG", "dD", "iI" },
            ['g'] = new[] { "fF", "7&", "8*", "cC", "hH", "dD" },
            ['h'] = new[] { "dD", "gG", "cC", "tT", "mM", "bB" },
            ['i'] = new[] { "uU", "yY", "fF", "dD", "xX", "kK" },
            ['j'] = new[] { "qQ", "eE", "uU", "kK", null, null },
            ['k'] = new[] { "jJ", "uU", "iI", "xX", null, null },
            ['l'] = new[] { "rR", "0)", "[{", "/?", "sS", "nN" },
            ['m'] = new[] { "bB", "hH", "tT", "wW", null, null },
            ['n'] = new[] { "tT", "rR", "lL", "sS", "vV", "wW" },
            ['o'] = new[] { "aA", ",<", ".>", "eE", "qQ", ";:" },
            ['p'] = new[] { ".>", "4$", "5%", "yY", "uU", "eE" },
            ['q'] = new[] { ";:", "oO", "eE", "jJ", null, null },
            ['r'] = new[] { "cC", "9(", "0)", "lL", "nN", "tT" },
            ['s'] = new[] { "nN", "lL", "/?", "-_", "zZ", "vV" },
            ['t'] = new[] { "hH", "cC", "rR", "nN", "wW", "mM" },
            ['u'] = new[] { "eE", "pP", "yY", "iI", "kK", "jJ" },
            ['v'] = new[] { "wW", "nN", "sS", "zZ", null, null },
            ['w'] = new[] { "mM", "tT", "nN", "vV", null, null },
            ['x'] = new[] { "kK", "iI", "dD", "bB", null, null },
            ['y'] = new[] { "pP", "5%", "6^", "fF", "iI", "uU" },
            ['z'] = new[] { "vV", "sS", "-_", null, null, null },
            ['{'] = new[] { "0)", null, null, "]}", "/?", "lL" },
            ['|'] = new[] { "=+", null, null, null, null, null },
            ['}'] = new[] { "[{", null, null, null, "=+", "/?" },
            ['~'] = new[] { null, null, null, "1!", null, null }
        };

        public static AdjacencyGraph Keypad = new AdjacencyGraph(nameof(Keypad))
        {
            ['*'] = new[] { "/", null, null, null, "-", "+", "9", "8" },
            ['+'] = new[] { "9", "*", "-", null, null, null, null, "6" },
            ['-'] = new[] { "*", null, null, null, null, null, "+", "9" },
            ['.'] = new[] { "0", "2", "3", null, null, null, null, null },
            ['/'] = new[] { null, null, null, null, "*", "9", "8", "7" },
            ['0'] = new[] { null, "1", "2", "3", ".", null, null, null },
            ['1'] = new[] { null, null, "4", "5", "2", "0", null, null },
            ['2'] = new[] { "1", "4", "5", "6", "3", ".", "0", null },
            ['3'] = new[] { "2", "5", "6", null, null, null, ".", "0" },
            ['4'] = new[] { null, null, "7", "8", "5", "2", "1", null },
            ['5'] = new[] { "4", "7", "8", "9", "6", "3", "2", "1" },
            ['6'] = new[] { "5", "8", "9", "+", null, null, "3", "2" },
            ['7'] = new[] { null, null, null, "/", "8", "5", "4", null },
            ['8'] = new[] { "7", null, "/", "*", "9", "6", "5", "4" },
            ['9'] = new[] { "8", "/", "*", "-", "+", null, "6", "5" }
        };

        public static AdjacencyGraph MacKeypad = new AdjacencyGraph(nameof(MacKeypad))
        {
            ['*'] = new[] { "/", null, null, null, null, null, "-", "9" },
            ['+'] = new[] { "6", "9", "-", null, null, null, null, "3" },
            ['-'] = new[] { "9", "/", "*", null, null, null, "+", "6" },
            ['.'] = new[] { "0", "2", "3", null, null, null, null, null },
            ['/'] = new[] { "=", null, null, null, "*", "-", "9", "8" },
            ['0'] = new[] { null, "1", "2", "3", ".", null, null, null },
            ['1'] = new[] { null, null, "4", "5", "2", "0", null, null },
            ['2'] = new[] { "1", "4", "5", "6", "3", ".", "0", null },
            ['3'] = new[] { "2", "5", "6", "+", null, null, ".", "0" },
            ['4'] = new[] { null, null, "7", "8", "5", "2", "1", null },
            ['5'] = new[] { "4", "7", "8", "9", "6", "3", "2", "1" },
            ['6'] = new[] { "5", "8", "9", "-", "+", null, "3", "2" },
            ['7'] = new[] { null, null, null, "=", "8", "5", "4", null },
            ['8'] = new[] { "7", null, "=", "/", "9", "6", "5", "4" },
            ['9'] = new[] { "8", "=", "/", "*", "-", "+", "6", "5" },
            ['='] = new[] { null, null, null, null, "/", "9", "8", "7" }
        };

        public string Name { get; }

        private AdjacencyGraph(string name)
        {
            Name = name;
        }
    }
}
